config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'
  post 'sessions/create'

  get 'admin', to: 'admin#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #controller :sessions do
  #  get 'login' => :new
  #  post 'login' => :create
  #  delete 'logout' => :destroy
  #end

  get 'sessions/destroy'

  resources :users
  get 'store/index'
  resources :products

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'store#index', as: 'store'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = <%= controller.controller_name %> >
    <div id = "banner">
      <h1>
        <%= @page_title || t('.title') %>
        <%= form_tag store_path, class: 'locale' do %>
          <%= select_tag 'set_locale',
            options_for_select(LANGUAGES, I18n.locale.to_s),
            onchange: 'this.form.submit()'
            %>
        <% end %>
      </h1>

    </div>
    <div id = "columns">
      <div id = "side">
        <div id = "cart"

          <% if @cart and @cart.line_items.empty? %>
            style = "display:none;"
          <% end %>
        >
        <% if @cart %>
          <%= render @cart %>
        <% end %>
      </div>
      <% if not session[:user_id] %>
        <ul>
          <li id = "login-bar"><%= link_to 'Log in', login_path %></li>
        </ul>
      <% else %>
        <ul>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
          <span id = "date">
            <%= Time.now %>
          </span>
          <li><a href = "#"> <%= t('.home') %></a></li>
          <li><a href = "#"> <%= t('.questions') %></a></li>
          <li><a href = "#"> <%= t('.news') %></a></li>
          <li><a href = "#"> <%= t('.contacts') %></a></li>
        </ul>
      </div>
      <div id = "main">
        <%= yield %>
      </div>
    </div>

  </body>
</html>